### ISSUE TITLE
Provide a way to include polyfills automagically

### ISSUE THREAD

**Issue by tylerball** [Shopify/babel-preset-shopify#12]
We use `babel-preset-shopify` in a lot of places, which is fantastic for getting build settings that work. However developers inevitably forget or don't know to include polyfills for es6 features we use and their apps break either in CI or in production and don't notice because everybody uses Chrome.

It would be great if we could provide a config here with the necessary polyfills automatically included and instruct people to use it along with something like the assets gem.

```
{
  babel: {
    preset: 'babel-preset-shopify/web'
  }
}
```

Sound good @Shopify/javascript ?

**Comment by GoodForOneFare** [comment]
babel-preset-shopify@16 uses [`babel-preset-env`](https://github.com/babel/babel-preset-env), which:

> can automatically determine the Babel plugins and polyfills you need based on your supported environments.

Are you using v16, @tylerball?
