### ISSUE TITLE
shopify/web with {modules: false} will fail

### ISSUE THREAD

**Issue by SidKwok** [Shopify/babel-preset-shopify#17]
Simply set `{modules: false}` in [draggable's webpack config](https://github.com/Shopify/draggable/blob/master/webpack.config.js), and you will get this:

![7331b8792598aaa107ba19e45542d0bc](https://user-images.githubusercontent.com/13268747/33198406-e847fbb2-d125-11e7-8a77-8b6e5a3a11f9.png)

Webpack3 should support the modules feature.

**Comment by alexandcote** [comment]
Since this project has moved and this issue is opened since 2017, I'm closing it. Feel free to open it again in the new repo if you still have an issue.
