### ISSUE TITLE
Add jsx fragment transform

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/babel-preset-shopify#26]
Lack of fragment support is a blocker for using `tsconfig.json#jsx = preserve`.

cc @lemonmade

**Comment by lemonmade** [comment]
Are we just out of date on the React preset?

**Comment by GoodForOneFare** [comment]
Yes and no.  We're using the latest `babel-preset-react` version.  We could use the `v7.0.0-beta.32` release, but that'll require a wholesale upgrade to babel@7.

A stopgap would be adding [`babel-plugin-jsx-fragment`](https://www.npmjs.com/package/babel-plugin-jsx-fragment).  My preference would be to just bite the bullet on babel@7.

**Comment by alexandcote** [comment]
Fragments are now supported since babel@7
