### ISSUE TITLE
error when bitbucket pipeline runs test cases.

### ISSUE THREAD

**Issue by sanchit121** [Shopify/babel-preset-shopify#32]
● Test suite failed to run
    Unexpected token ) (While processing preset: "/opt/atlassian/pipelines/agent/build/node_modules/babel-preset-shopify/node.js")
      
      at Object.<anonymous> (node_modules/babel-preset-shopify/node.js:1:90)

However, locally the same thing is working fine.

**Comment by GoodForOneFare** [comment]
Hi @sanchit121!  My best guess is that the Bitbucket pipeline is using an old version of Node.  I suggest updating it to use the latest Node version.

If that doesn't help, please respond with:
- Your `babel-preset-shopify` version
- Your local Node version
- Your pipeline's Node version

**Comment by alexandcote** [comment]
Since this project has moved and this issue is opened since 2018, I'm closing it. Feel free to open it again in the [new repo](https://github.com/shopify/web-foundation)
